export const ALBUM_ADDED = 'ALBUM_ADDED';
export const ALBUMS_CLEAR = 'ALBUMS_CLEAR';
export const ALBUMDROPDOWN_ADDED = 'ALBUMDROPDOWN_ADDED';
export const ALBUMDROPDOWN_CLEAR = 'ALBUMDROPDOWN_CLEAR';
export const ALBUM_SELECTED = 'ALBUM_SELECTED';
export const ALBUM_DESELECTED = 'ALBUM_DESELECTED';
