export const PERMISSION_ADDED = 'PERMISSION_ADDED';
export const PERMISSIONS_CLEAR = 'PERMISSIONS_CLEAR';
export const PERMISSION_SELECTED = 'PERMISSION_SELECTED';
export const PERMISSION_DESELECTED = 'PERMISSION_DESELECTED';
