export const TRACK_ADDED = 'TRACK_ADDED';
export const TRACKS_CLEAR = 'TRACKS_CLEAR';
export const TRACK_LISTEN = 'TRACK_LISTEN';
export const TRACK_SELECTED = 'TRACK_SELECTED';
export const TRACK_DESELECTED = 'TRACK_DESELECTED';
